/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "tftp.h"

bool_t
xdr_ErrCode (XDR *xdrs, ErrCode *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Mode (XDR *xdrs, Mode *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_errstr_t (XDR *xdrs, errstr_t *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAX_STRING_ERR_LEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_filename_t (XDR *xdrs, filename_t *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAX_FILE_NAME_LENGTH))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_data_block_t (XDR *xdrs, data_block_t *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->data_block_t_val, (u_int *) &objp->data_block_t_len, MAX_DAT_LENGTH))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_request_t (XDR *xdrs, request_t *objp)
{
	register int32_t *buf;

	 if (!xdr_filename_t (xdrs, &objp->fn))
		 return FALSE;
	 if (!xdr_Mode (xdrs, &objp->mode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_sess_t (XDR *xdrs, sess_t *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_error_t (XDR *xdrs, error_t *objp)
{
	register int32_t *buf;

	 if (!xdr_sess_t (xdrs, &objp->sess_id))
		 return FALSE;
	 if (!xdr_errstr_t (xdrs, &objp->err))
		 return FALSE;
	 if (!xdr_ErrCode (xdrs, &objp->code))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_res_t (XDR *xdrs, res_t *objp)
{
	register int32_t *buf;

	 if (!xdr_bool (xdrs, &objp->success))
		 return FALSE;
	switch (objp->success) {
	case FALSE:
		 if (!xdr_error_t (xdrs, &objp->res_t_u.err))
			 return FALSE;
		break;
	case TRUE:
		 if (!xdr_sess_t (xdrs, &objp->res_t_u.sess_id))
			 return FALSE;
		break;
	default:
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_datapacket_t (XDR *xdrs, datapacket_t *objp)
{
	register int32_t *buf;

	 if (!xdr_sess_t (xdrs, &objp->sess_id))
		 return FALSE;
	 if (!xdr_data_block_t (xdrs, &objp->blk))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_dataret_t (XDR *xdrs, dataret_t *objp)
{
	register int32_t *buf;

	 if (!xdr_bool (xdrs, &objp->success))
		 return FALSE;
	switch (objp->success) {
	case FALSE:
		 if (!xdr_error_t (xdrs, &objp->dataret_t_u.err))
			 return FALSE;
		break;
	case TRUE:
		 if (!xdr_data_block_t (xdrs, &objp->dataret_t_u.blk))
			 return FALSE;
		break;
	default:
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_data_t (XDR *xdrs, data_t *objp)
{
	register int32_t *buf;

	 if (!xdr_sess_t (xdrs, &objp->sess_id))
		 return FALSE;
	 if (!xdr_dataret_t (xdrs, &objp->data))
		 return FALSE;
	return TRUE;
}
