/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "tftp.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
tftp_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		request_t get_file_1_arg;
		request_t put_file_1_arg;
		sess_t get_block_1_arg;
		datapacket_t put_block_1_arg;
		error_t error_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case GET_FILE:
		_xdr_argument = (xdrproc_t) xdr_request_t;
		_xdr_result = (xdrproc_t) xdr_res_t;
		local = (char *(*)(char *, struct svc_req *)) get_file_1_svc;
		break;

	case PUT_FILE:
		_xdr_argument = (xdrproc_t) xdr_request_t;
		_xdr_result = (xdrproc_t) xdr_res_t;
		local = (char *(*)(char *, struct svc_req *)) put_file_1_svc;
		break;

	case GET_BLOCK:
		_xdr_argument = (xdrproc_t) xdr_sess_t;
		_xdr_result = (xdrproc_t) xdr_data_t;
		local = (char *(*)(char *, struct svc_req *)) get_block_1_svc;
		break;

	case PUT_BLOCK:
		_xdr_argument = (xdrproc_t) xdr_datapacket_t;
		_xdr_result = (xdrproc_t) xdr_res_t;
		local = (char *(*)(char *, struct svc_req *)) put_block_1_svc;
		break;

	case ERROR:
		_xdr_argument = (xdrproc_t) xdr_error_t;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) error_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;
	
	if(argc==2){
		int tlevel = atoi(argv[1]);
		SET_TRACE_LEVEL(tlevel);
	}
	
	pmap_unset (TFTP_PROG, TFTP_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, TFTP_PROG, TFTP_VERS, tftp_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (TFTP_PROG, TFTP_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, TFTP_PROG, TFTP_VERS, tftp_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (TFTP_PROG, TFTP_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
