/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "tftp.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

res_t *
get_file_1(request_t *argp, CLIENT *clnt)
{
	static res_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GET_FILE,
		(xdrproc_t) xdr_request_t, (caddr_t) argp,
		(xdrproc_t) xdr_res_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

res_t *
put_file_1(request_t *argp, CLIENT *clnt)
{
	static res_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, PUT_FILE,
		(xdrproc_t) xdr_request_t, (caddr_t) argp,
		(xdrproc_t) xdr_res_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

data_t *
get_block_1(sess_t *argp, CLIENT *clnt)
{
	static data_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GET_BLOCK,
		(xdrproc_t) xdr_sess_t, (caddr_t) argp,
		(xdrproc_t) xdr_data_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

res_t *
put_block_1(datapacket_t *argp, CLIENT *clnt)
{
	static res_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, PUT_BLOCK,
		(xdrproc_t) xdr_datapacket_t, (caddr_t) argp,
		(xdrproc_t) xdr_res_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

void *
error_1(error_t *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, ERROR,
		(xdrproc_t) xdr_error_t, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}
