
/* ------------------------------------------
   Automatically generated by AN
   ------------------------------------------ */

package it.unibo.is.interfaces.platforms;

public interface IMedCl09 extends IOpIn, IOpOut{
	
}
