
/* ------------------------------------------
   Automatically generated by AN
   ------------------------------------------ */

package it.unibo.is.interfaces.platforms;
import it.unibo.is.interfaces.IMessage;

	public interface IMessageAndContext {
	 	public void replyToCaller(String msg) throws Exception;
	 	public IMessage getReceivedMessage();
	}
